# Generated by Django 5.1 on 2024-09-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('aluno_id', models.AutoField(primary_key=True, serialize=False)),
                ('aluno_nome', models.CharField(max_length=255)),
                ('aluno_nascimento', models.DateField()),
                ('aluno_nome_mae', models.CharField(max_length=255)),
                ('aluno_nascimento_mae', models.DateField()),
                ('aluno_nome_pai', models.CharField(max_length=255)),
                ('aluno_nascimento_pai', models.DateField()),
                ('aluno_cep', models.CharField(max_length=15)),
                ('aluno_endereco', models.CharField(max_length=255)),
                ('aluno_bairro', models.CharField(max_length=150)),
                ('aluno_cidade', models.CharField(max_length=150)),
                ('aluno_estado', models.CharField(max_length=50)),
                ('aluno_telefone', models.CharField(max_length=100)),
                ('aluno_email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('aula_id', models.AutoField(primary_key=True, serialize=False)),
                ('aula_descricao', models.CharField(max_length=50)),
                ('aula_data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PresencaAula',
            fields=[
                ('pres_id', models.AutoField(primary_key=True, serialize=False)),
                ('pres_aluno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_escolinha.aluno')),
                ('pres_aula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_escolinha.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('prof_id', models.AutoField(primary_key=True, serialize=False)),
                ('prof_nome', models.CharField(max_length=50)),
                ('prof_telefone', models.CharField(max_length=50)),
                ('prof_email', models.CharField(max_length=100)),
                ('prof_nascimento', models.DateField()),
                ('prof_cep', models.CharField(max_length=15)),
                ('prof_endereco', models.CharField(max_length=255)),
                ('prof_bairro', models.CharField(max_length=150)),
                ('prof_cidade', models.CharField(max_length=150)),
                ('prof_estado', models.CharField(max_length=50)),
                ('prof_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_escolinha.status')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_escolinha.status'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('turma_id', models.AutoField(primary_key=True, serialize=False)),
                ('turma_descricao', models.CharField(max_length=50)),
                ('turma_idade_limite', models.BigIntegerField()),
                ('turma_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_escolinha.status')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorTurma',
            fields=[
                ('prof_turma_id', models.AutoField(primary_key=True, serialize=False)),
                ('prof_turma_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escolinha.professor')),
                ('prof_turma_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escolinha.turma')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='aula_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_escolinha.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_escolinha.turma'),
        ),
    ]
